# Generated by Whalepod.
.DEFAULT_GOAL := all
.PHONY: 26.0 27.0 28.0 29.0 30.0

26.0:
	docker build -t landyrev/flutter-fastlane-android:26.0 ./26.0 
27.0:
	docker build -t landyrev/flutter-fastlane-android:27.0 ./27.0 
28.0:
	docker build -t landyrev/flutter-fastlane-android:28.0 ./28.0 
29.0:
	docker build -t landyrev/flutter-fastlane-android:29.0 ./29.0 
30.0:
	docker build -t landyrev/flutter-fastlane-android:30.0 ./30.0 
all: 26.0 27.0 28.0 29.0 30.0